### ISSUE TITLE
Stackimpact itself allocated too much memory!

### ISSUE THREAD

**Issue by yaodd** [stackimpact/stackimpact-go#2] opened 2016-11-25 02:42 UTC
![8bf8wupo upo_puo 2ilckj](https://cloud.githubusercontent.com/assets/5771173/20613125/c346dd54-b2fb-11e6-939c-ef2abcfd3412.png)

Hello,I used the library stackimpact in my program yesterday. I found stackimpack itself allocated too much memory just now. Is there any way to optimize it ?

**Comment by dmelikyan** [comment] 2016-11-25 08:00
Thanks for reporting this! Could you also add the agent version to the issue? You can find it in internal/agent.go or enable debug mode with `agent.Debug = true` and it will be in the prefix of log messages.

Regular memory spikes are caused by reading the tracing log and generating profiles out of it, which is expected. It is visible in this case, because it overlapped with reading memory profile.

However, it should never be these high. We're already looking into it.

**Comment by dmelikyan** [comment] 2016-11-26 16:21
Fixed in agent version 1.1.4. The agent will adjust tracing duration based on load to prevent memory usage spikes when processing traced events.

**Closed by dmelikyan** 2016-11-26 16:21 UTC
Labels: bug
